# mysql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - name: mysql-server
        image: mysql:5.7
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: laravel
---
# phpmyadmin 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: PMA_ARBITRARY
          value: "1"
---
# laravel-vue application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-vue
spec:
  selector:
    matchLabels:
      app: laravel-vue
  template:
    metadata:
      labels:
        app: laravel-vue
    spec:
      containers:
      - name: laravel-vue
        image: laravel-vue:final
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: APP_URL
          value: "http://localhost:8000"
        - name: APP_ENDPOINT_PORT
          value: "8000"
        - name: DB_HOST
          value: "mysql-server"
        - name: DB_DATABASE
          value: "laravel"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "password"
